# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


before_all do |lane, options|
  'defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES'
end

desc "Run all tests"
lane :test do
run_tests(
  scheme: "testable-view-swiftui",
  only_testing: ["TestableAppUITests"],
  clean: false,
  devices: ["iPhone 16"]
)
run_tests(
  scheme: "testable-view-swiftui",
  only_testing: ["TestableAppTests"],
  clean: false,
  devices: ["iPhone 16"]
)
end
